<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.bees.testcases.Prac" tests="1" time="4.590" ignored="6" failures="1" timestamp="23 May 2021 14:06:14 GMT" skipped="0" hostname="Kalyani" errors="0">
  <testcase name="URLoneReadMoreOfHomePg" time="4.590" classname="com.bees.testcases.Prac">
    <failure type="java.lang.AssertionError" message="expected [http://javabykiran.in/Other/thbees/blog/organic-gifts] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [http://javabykiran.in/Other/thbees/blog/organic-gifts] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:130)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.bees.testcases.Prac.URLoneReadMoreOfHomePg(Prac.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- URLoneReadMoreOfHomePg -->
  <testcase name="sssReadMore" classname="com.bees.testcases.Prac">
    <skipped/>
  </testcase> <!-- sssReadMore -->
  <testcase name="validDtaInSearch" classname="com.bees.testcases.Prac">
    <skipped/>
  </testcase> <!-- validDtaInSearch -->
  <testcase name="getData" classname="com.bees.testcases.Prac">
    <skipped/>
  </testcase> <!-- getData -->
  <testcase name="test" classname="com.bees.testcases.Prac">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="ttt" classname="com.bees.testcases.Prac">
    <skipped/>
  </testcase> <!-- ttt -->
  <testcase name="oneReadMoreOfHomePg" classname="com.bees.testcases.Prac">
    <skipped/>
  </testcase> <!-- oneReadMoreOfHomePg -->
</testsuite> <!-- com.bees.testcases.Prac -->
